### ISSUE TITLE
Is this official implementation?

### ISSUE THREAD

**Issue by yd-yin** [phelps-matthew/implicit-pdf#1]
Hi, 
Really thanks for your implementation!

Just to ask is this an official PyTorch implementation or a re-implementation in PyTorch?

Thanks

**Comment by phelps-matthew** [comment]
You're welcome! This is not an official as sanctioned by the authors, but rather just a re-implementation I made myself.

**Comment by phelps-matthew** [comment]
However it is the only pytorch implementation as I'm aware. Most of the repo follows the original closely.

**Comment by yd-yin** [comment]
I got it. Thanks for your effort and for sharing the code!

Just one little tip, if you also show the results of the repo (comparing with the original results), it would be even more helpful.
